# Generated by Django 5.1.1 on 2024-09-04 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 4, 11, 35, 18, 699404)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 4, 11, 35, 34, 916176)),
            preserve_default=False,
        ),
    ]
