# Generated by Django 5.1.1 on 2024-09-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='../1default_profile_f2n1za', upload_to='images/'),
        ),
    ]
