# Generated by Django 5.1.1 on 2024-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
