# Generated by Django 5.1.1 on 2024-09-18 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('generative-art', 'Generative Art'), ('digital-illustrations-and-paintings', 'Digital Illustrations and Paintings'), ('pixel-art', 'Pixel Art'), ('3d-artwork', '3D Artwork'), ('photography', 'Photography'), ('augmented-reality-art', 'Augmented Reality Art'), ('collage-art', 'Collage Art'), ('interactive-art', 'Interactive Art'), ('music-and-audio-art', 'Music and Audio Art'), ('ai-generated-art', 'AI-Generated Art'), ('fine-art-nfts', 'Fine Art NFTs'), ('other', 'Other')], default=None, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default='../default_art_image_axpg76', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagged_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
