# Generated by Django 5.1.1 on 2024-09-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
        ('geolocation', '0002_geolocation_city_geolocation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='geolocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.geolocation'),
        ),
    ]
